version: '3.8'

services:
  osm-processor:
    image: ghcr.io/openstreetmap/osmium-tool:latest
    container_name: osm-processor
    volumes:
      - ./raw_data/data_osm:/data
      - ./output/osm_processed:/output
    working_dir: /data
    command: /bin/sh
    stdin_open: true
    tty: true
    networks:
      - data_us_100k_pop_default

  gdal-processor:
    image: ghcr.io/osgeo/gdal:ubuntu-small-latest
    container_name: gdal-processor
    volumes:
      - ./raw_data/data_osm:/data
      - ./output/osm_processed:/output
      - ./scripts:/scripts
    working_dir: /data
    command: /bin/bash
    stdin_open: true
    tty: true
    networks:
      - data_us_100k_pop_default

  osm-python:
    build:
      context: .
      dockerfile: Dockerfile.osm
    container_name: osm-python
    volumes:
      - ./raw_data/data_osm:/data
      - ./output/osm_processed:/output
      - ./scripts:/scripts
    working_dir: /data
    command: /bin/bash
    stdin_open: true
    tty: true
    networks:
      - data_us_100k_pop_default

networks:
  data_us_100k_pop_default:
    external: true