version: '3.8'

services:
  postgres:
    image: postgis/postgis:15-3.3
    container_name: roads-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: roadsdb2024secure
      POSTGRES_DB: roads_db
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./postgres-backups:/backups
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: >
      postgres
      -c shared_buffers=1GB
      -c effective_cache_size=3GB
      -c maintenance_work_mem=256MB
      -c work_mem=64MB
      -c max_connections=200
      -c random_page_cost=1.1
      -c effective_io_concurrency=200