version: '3.8'

services:
  postgres:
    image: postgis/postgis:15-3.3
    container_name: roads-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: roads_db
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./scripts:/scripts
    ports:
      - "5432:5432"
    # Increase shared memory size
    shm_size: '2gb'
    # PostgreSQL tuning for large operations
    command: |
      postgres
      -c shared_buffers=1GB
      -c work_mem=256MB
      -c maintenance_work_mem=512MB
      -c effective_cache_size=2GB
      -c max_wal_size=2GB
      -c checkpoint_timeout=30min
      -c checkpoint_completion_target=0.9
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: roads-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@roads.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
